### PR TITLE
Use external PRP repo

### LINKED ISSUE #225: Pipeline results processor: Should be moved to it's on repository
Seeing as prp is more specific to Bonsai than anything else, we should move it to its own repository where Bonsai is being developed so it can be maintained side by side and in accordance to the needs of Bonsai. This will mean that the Makefile will now need to clone it into the same directory and pip install it.

### PR DESCRIPTION
**Pull request by mhkc**
# Description

This PR installs PRP from its repository. Close #225 

_Summary of the changes made:_
Install PRP from repo.

## Primary function of PR
- [x] Hotfix
- [ ] Minor functionality improvement
- [ ] Major functionality improvement / New type of analysis
- [ ] Backward-breaking functionality

# Testing
_Either describe a procedure, or add data; that confirms that the PR resolves what it sets out to do_

# Sign-offs
- [ ] Code reviewed by @octocat
- [ ] Code tested by @octocat

### CODE REVIEW

**Review by sylvinite — APPROVED** [review]
Structure looks good. Just make sure to test it.

**Comment by ryanjameskennedy** [comment]
Will my changes in PR #233 affect this at all @mhkc?

**Comment by mhkc** [comment]
I have tested PRP with S. aureus, E. coli and M. tuberculosis pipelines from the current master.

**Review by ryanjameskennedy — APPROVED** [review]
LGTM!

**Pull request merged**
