### PR TITLE
Fix #237: Upgrade Skesa container to 2.5.1 to fix ownership issue with /tmp

### LINKED ISSUE #237: Can not bind to sub-folders of /tmp in skesa container
For the Skesa process and container (version 2.4.0), we have repeatedly got errors like this, unless using a temporary folder outside of `/tmp`:

```log
Dec-13 11:27:59.352 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:skesa (ATCC29213); work-dir=<snip>/jasen/work/de/e14dbd88a4fac8dcd57be953670207
  error [nextflow.exception.ProcessFailedException]: Process `CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:skesa (ATCC29213)` terminated with an error exit status (255)
Dec-13 11:27:59.385 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:skesa (ATCC29213)'

Caused by:
  Process `CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:skesa (ATCC29213)` terminated with an error exit status (255)

Command executed:

  skesa --reads 230904_ATCC29213_1.fastq.gz,230904_ATCC29213_2.fastq.gz --cores 16 --memory 32 > ATCC29213.fasta
  
  cat <<-END_VERSIONS > ATCC29213_CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:skesa_versions.yml
  CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:skesa:
   skesa:
    version: $(echo $(skesa --version 2>&1) | sed 's/^.*SKESA // ; s/ .*//')
    container: <snip>/jasen/container/skesa.sif
  END_VERSIONS

Command exit status:
  255

Command output:
  (empty)

Command error:
  WARNING: While bind mounting '/tmp:/tmp/': destination is already in the mount point list
  FATAL:   container creation failed: mount /tmp/nxf.vvKUU5fXbC->/tmp/nxf.vvKUU5fXbC error: while mounting /tmp/nxf.vvKUU5fXbC: destination /tmp/nxf.vvKUU5fXbC doesn't exist in container

Work dir:
  <snip>/jasen/work/de/e14dbd88a4fac8dcd57be953670207
```

After investigating, it turns out that for the skesa container, binding to sub-folders of `/tmp` does not work unless the folder is first created inside the container.

Checking the ownership of the `/tmp` folders in all our containers, reveal that only in the Skesa one, it is owned by root:

```bash
[shl container]$ for cont in $(ls *.sif | grep -v _); do name="$cont........"; echo ${name:0:16} ":" $(singularity exec $cont ls -ld /tmp); done
abritamr.sif.... : drwxrwxrwt 36 shl shl 20480 Dec 13 12:54 /tmp
amrfinderplus.si : drwxrwxrwt 36 shl shl 20480 Dec 13 12:54 /tmp
blast.sif....... : drwxrwxrwt 36 shl shl 20480 Dec 13 12:54 /tmp
bracken.sif..... : drwxrwxrwt 36 shl shl 20480 Dec 13 12:54 /tmp
bwakit.sif...... : drwxrwxrwt 36 shl shl 20480 Dec 13 12:54 /tmp
chewbbaca.sif... : drwxrwxrwt 36 shl shl 20480 Dec 13 12:54 /tmp
freebayes.sif... : drwxrwxrwt 36 shl shl 20480 Dec 13 12:54 /tmp
kraken2.sif..... : drwxrwxrwt 36 shl shl 20480 Dec 13 12:54 /tmp
mlst.sif........ : drwxrwxrwt 36 shl shl 20480 Dec 13 12:54 /tmp
mykrobe.sif..... : drwxrwxrwt 36 shl shl 20480 Dec 13 12:54 /tmp
postAlignQc.sif. : drwxrwxrwt 36 shl shl 20480 Dec 13 12:54 /tmp
pythonScripts.si : drwxrwxrwt 36 shl shl 20480 Dec 13 12:54 /tmp
quast.sif....... : drwxrwxrwt 36 shl shl 20480 Dec 13 12:54 /tmp
resfinder.sif... : drwxrwxrwt 36 shl shl 20480 Dec 13 12:54 /tmp
samtools.sif.... : drwxrwxrwt 36 shl shl 20480 Dec 13 12:54 /tmp
skesa.sif....... : drwxrwxrwt 40 root root 4096 Dec 13 12:41 /tmp
snippy.sif...... : drwxrwxrwt 36 shl shl 20480 Dec 13 12:54 /tmp
sourmash.sif.... : drwxrwxrwt 36 shl shl 20480 Dec 13 12:54 /tmp
spades.sif...... : drwxrwxrwt 36 shl shl 20480 Dec 13 12:54 /tmp
tbprofiler.sif.. : drwxrwxrwt 36 shl shl 20480 Dec 13 12:54 /tmp
virulencefinder. : drwxrwxrwt 36 shl shl 20480 Dec 13 12:54 /tmp
```

This is not the case in the new Skesa 2.5.1 container, this is not the case, so upgrading Skesa to 2.5.1 seems like a potential solution.

### PR DESCRIPTION
**Pull request by samuell**
# Description

See #237 

This PR fixes #237 by upgrading the Skesa container to version 2.5.1.

## Primary function of PR
- [x] Hotfix
- [ ] Minor functionality improvement
- [ ] Major functionality improvement / New type of analysis
- [ ] Backward-breaking functionality

# Testing

- Have been running the full staphylococcu_aureus workflow on 5 samples of real data, up until running into #243 

# Sign-offs
- [ ] Code reviewed by @octocat
- [ ] Code tested by @octocat

### CODE REVIEW

**Review by sylvinite — APPROVED** [review]

**Comment by samuell** [comment]
Just noting Ryan's question, from Slack:

> [Ryan James Kennedy](https://genomicmedicinesweden.slack.com/archives/C012NJWJLN8/p1702545026033839?thread_ts=1702469214.395429&cid=C012NJWJLN8)
> We need test samples for all the species we run to check that updates of software work across the board. Is that possible to organise @Isak Sylvin

**Comment by ryanjameskennedy** [comment]
@mhkc where did you find those test reads for tb? Or did you just simulate reads from the reference genome? ([wgsim](https://github.com/lh3/wgsim) is a good tool for this btw)?

**Comment by mhkc** [comment]
I just took public samples from EBI that were relevant and with good sequencing depth.

**Comment by samuell** [comment]
(WIP) Testing some AMR Klebsiella data:

The following are correctly typed as carbapenem resistant:
- https://www.ebi.ac.uk/ena/browser/view/SRR12149874
- https://www.ebi.ac.uk/ena/browser/view/SRR12149876
- https://www.ebi.ac.uk/ena/browser/view/SRR4191406 (res + amr-finder)
- https://www.ebi.ac.uk/ena/browser/view/SRR4191407

These strains are supposed to be colistin resistant (according to description), but is only typed as susceptible by resfinder (no colistin from amrfinder):
- https://www.ebi.ac.uk/ena/browser/view/SRR15293794
- https://www.ebi.ac.uk/ena/browser/view/SRR3174988

**Pull request merged**
