### PR TITLE
Add seq run and lims id to bonsai input

### PR DESCRIPTION
**Pull request by ryanjameskennedy**
# Description
_Summary of the changes made:_
* Added `lims_id` & `sequencing_run` to `meta` module
* Renamed `nextflow.hopper.config` to `nextflow.dev.config` for hopper development

## Primary function of PR
- [x] Hotfix

# Testing
Tested on saureus samples

### CODE REVIEW

**Review by mhkc — APPROVED** [review]
Looks good

**Review by mhkc — CHANGES_REQUESTED** [review]
I think we should hold of with this one for a bit

**Comment by ryanjameskennedy** [comment]
> I think we should hold of with this one for a bit until Bonsai has been updated.

I don't agree. Without the model update from prp being in a release that the other configs aren't using, `sequencing_run`and `lims_id` won't be added to the bonsai input (aka prp output). Though prp still runs (I've tested it).

**Comment by mhkc** [comment]
Good point. We can roll it but I would like to get the delly annotations in a update before we run through all samples.

**Review by mhkc — APPROVED** [review]

**Pull request merged**
