### PR TITLE
Implement #260: Implement a basic CI test-run pipeline in Github Actions

### PR DESCRIPTION
**Pull request by samuell**
# Description

It is great if we can have a GH Actions workflow that runs the test-run in an automatically set-up container, to make sure that nothing is accidentally broken, some dependencies are missing or similar.

This PR also contains a Dockerfile and scripts specifically for being able to run the GitHub Actions workflow also locally (but containerized in Docker) using the [act](https://github.com/nektos/act) tool, as that should be able to speed up the iteration loop when fixing bugs, as not needing to push to GitHub just to run the test pipeline.

## Primary function of PR
- [ ] Hotfix
- [x] Minor functionality improvement
- [ ] Major functionality improvement / New type of analysis
- [ ] Backward-breaking functionality

# Testing

This will run automated testing as part of a GitHub Actions workflow.

# Sign-offs
- [ ] Code reviewed by @octocat
- [ ] Code tested by @octocat

### CODE REVIEW

**Comment by samuell** [comment]
Well, CI via GitHub actions work now, at least for S. Aureus, if separating the installation process per organism, which slashes the storage needs a lot.

**Review by ryanjameskennedy — COMMENTED** [review]
My only comment is the filepath of the `ci/` directory. Would it be possible to put it in the `.github/` directory as it pertains to github actions/workflows?

**Comment by samuell** [comment]
> My only comment is the filepath of the `ci/` directory. Would it be possible to put it in the `.github/` directory as it pertains to github actions/workflows?

Indeed, great point. Will fix!

**Comment by samuell** [comment]
> > My only comment is the filepath of the `ci/` directory. Would it be possible to put it in the `.github/` directory as it pertains to github actions/workflows?
> 
> Indeed, great point. Will fix!

Fixed now!

**Review by ryanjameskennedy — COMMENTED** [review]
Same for `scripts/` I reckon... Sorry to be a pain.

**Comment by samuell** [comment]
> Same for `scripts/` I reckon... Sorry to be a pain.

No worries at all, great with feedback! I saw this one and thought it might make sense to have it more exposed to users, but I'm fine with moving it in there (fixing...)

**Comment by samuell** [comment]
> > Same for `scripts/` I reckon... Sorry to be a pain.
> 
> No worries at all, great with feedback! I saw this one and thought it might make sense to have it more exposed to users, but I'm fine with moving it in there (fixing...)

Fixed now. does it look OK?

**Review by ryanjameskennedy — APPROVED** [review]
LGTM!

**Pull request merged**
